### ISSUE TITLE
Please, update the link channels to download versions in the JED

### ISSUE THREAD

**Issue by uzielweb** [Valc/jmlocalise#11]
We have ambiguous version links for Joomla 3, Joomla 4, and Joomla 5 on the JED. 
Please check the correct links on the JED. 
Additionally, I suggest to create a landing page on Github.io to host the useful information for the project. 

You can check how to do this at: [GitHub Pages](https://pages.github.com/).

**Comment by Valc** [comment]
I've never put anything from this fork of com_localise into JED, so I don't know what I could update: Nothing, I think.

The official version of com_localise is here:

https://github.com/joomla-projects/com_localise

And this version is a continuation of the code which I have known for years because I have contributed some lines of code on what we already had working under the leadership and supervision of JM Simonet.

In the JED and as far as I know, variants of the same development are not accepted, what should be linked there is the official project, or the fork should be renamed to avoid confusion.

No idea about official or non official codelines from  other places, except the last official version stopped working on J4 a long time ago.
