### ISSUE TITLE
Localise 5.0.1 RC3 creating 403 error when saving

### ISSUE THREAD

**Issue by sgagner** [Valc/jmlocalise#2]
When saving some files, not necessary large ones, localise creates a 403 error massage when saving. It seems like the changes are saved but the page can't be rendered again after save.

Localise runs on Joomla 4.2.9 and PHP 7.4 with max_input_vars set to 10000

**Comment by Valc** [comment]
Hi :)
The com_localise is a forward development, since from Joomla 5.x, you can continue to handle J3+ translations, if that were necessary: ​​you just have to change the configuration of the "Local installed instance" to the previous version from which you want to start working on the translation, and you can review all the text changes and new features from that moment to the latest development.

I don't know if your problem persists, but it is recommended to use the com_localise from the most recent version released as stable by the Joomla Project, and, in case of errors, try to provide the lines of code where our code causes errors that stop the program from working or some steps to follow to try to replicate the same error.
